services:
  trebuchet-web:
    image: ghcr.io/mitchellvanwagoner/trebuchet-simulator:latest
    pull_policy: always
    ports:
      - "8501:8501"
    environment:
      - TREBUCHET_OPT_WORKERS=${TREBUCHET_OPT_WORKERS:--1}
    volumes:
      - ./outputs:/app/outputs
      - /mnt/user/appdata/treb-sim:/app/data
